# Generated by Django 5.0.6 on 2024-05-27 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('product_price', models.TextField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('product_qty', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('price', models.FloatField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('stock', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='Store.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='Store.product')),
            ],
        ),
    ]
