# Generated by Django 5.0.6 on 2024-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.FileField(default=' ', upload_to='uploads/'),
        ),
    ]
